Repository son-s-minpark/aura-talk-back, pull requests merged in 2025-04, with the labels that each got.

#4 [BE] 로그인 구현
  Dockerfile
  docker-compose.yml
  src/main/java/com/sonsminpark/auratalkback/domain/user/controller/UserController.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/LoginRequestDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/UserDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/response/LoginResponseDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/entity/User.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/entity/UserStatus.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/exception/DuplicateUserException.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/exception/InvalidUserCredentialsException.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/exception/UserNotFoundException.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/repository/UserRepository.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/UserService.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/UserServiceImpl.java
  src/main/java/com/sonsminpark/auratalkback/global/common/ApiResponse.java
  src/main/java/com/sonsminpark/auratalkback/global/config/RedisConfig.java
  src/main/java/com/sonsminpark/auratalkback/global/config/SecurityConfig.java
  src/main/java/com/sonsminpark/auratalkback/global/exception/BusinessException.java
  src/main/java/com/sonsminpark/auratalkback/global/exception/ErrorCode.java
  src/main/java/com/sonsminpark/auratalkback/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sonsminpark/auratalkback/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sonsminpark/auratalkback/global/jwt/JwtTokenProvider.java
  src/main/java/com/sonsminpark/auratalkback/global/security/CustomUserDetailsService.java
  src/main/java/com/sonsminpark/auratalkback/global/security/TokenBlacklistService.java
  src/main/resources/application.yml
Labels: priority: high, api, backend, documentaion

#6 [BE] 회원가입/회원탈퇴 및 프로필 설정 구현
  build.gradle
  src/main/java/com/sonsminpark/auratalkback/domain/user/controller/UserController.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/EmailResendRequestDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/EmailVerificationRequestDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/ProfileSetupRequestDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/UserDeleteRequestDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/UserDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/response/SignUpResponseDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/entity/User.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/exception/InvalidUserInputException.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/repository/UserRepository.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/scheduler/UserDeletionScheduler.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/EmailService.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/EmailServiceImpl.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/UserService.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/UserServiceImpl.java
  src/main/java/com/sonsminpark/auratalkback/global/config/SchedulingConfig.java
  src/main/java/com/sonsminpark/auratalkback/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: priority: high, api, backend

#10 [BE] 사용자 이메일 인증 비활성화 및 예외 처리 통일
  src/main/java/com/sonsminpark/auratalkback/domain/user/exception/InvalidUserCredentialsException.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/exception/InvalidUserInputException.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/exception/UserNotFoundException.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/UserServiceImpl.java
Labels: refactor, priority: low, api, backend

#11 [BE] 프로필 조회 및 랜덤 채팅 설정 구현
  src/main/java/com/sonsminpark/auratalkback/domain/user/controller/UserController.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/ChatSettingsRequestDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/request/ProfileSetupRequestDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/entity/User.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/UserService.java
  src/main/java/com/sonsminpark/auratalkback/domain/user/service/UserServiceImpl.java
  src/main/java/com/sonsminpark/auratalkback/global/config/SecurityConfig.java
  src/main/java/com/sonsminpark/auratalkback/global/config/SwaggerConfig.java
  src/main/java/com/sonsminpark/auratalkback/global/jwt/JwtAuthenticationFilter.java
Labels: priority: medium, api, backend

#13 [BE] 무중단 배포 CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
  Dockerfile
  src/main/java/com/sonsminpark/auratalkback/global/config/SecurityConfig.java
  src/main/java/com/sonsminpark/auratalkback/global/config/SwaggerConfig.java
  src/main/java/com/sonsminpark/auratalkback/global/health/HealthController.java
  src/main/java/com/sonsminpark/auratalkback/global/jwt/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: priority: medium, api, backend, deploy

#15 [BE] Spring Security CORS 설정 비활성화
  src/main/java/com/sonsminpark/auratalkback/global/config/SecurityConfig.java
Labels: priority: high, backend, deploy

#19 [BE] CustomUserDetails 구현으로 사용자 인증 정보 관리 개선
  src/main/java/com/sonsminpark/auratalkback/global/security/CustomUserDetails.java
  src/main/java/com/sonsminpark/auratalkback/global/security/CustomUserDetailsService.java
Labels: refactor, backend
